webimage_extra_packages:
 - libnss3
 - libatk1.0-0
 - libatk-bridge2.0-0
 - libcups2
 - libgbm1
 - libxkbcommon0
 - libpango-1.0-0
 - libxcomposite1
 - libxcursor1
 - libxdamage1
 - libxi6
 - libxtst6
 - libxrandr2
 - libasound2
